/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author 12a24
 */
public class ParentForm extends javax.swing.JFrame {

    /**
     * Creates new form ParentForm
     */
    public ParentForm() {
        initComponents();

        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuForm = new javax.swing.JMenu();
        mnuItemInfo = new javax.swing.JMenuItem();
        mnuCategory = new javax.swing.JMenuItem();
        mnuBill = new javax.swing.JMenuItem();
        mnuBooking = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSearch = new javax.swing.JMenuItem();
        mnuAllBills = new javax.swing.JMenuItem();
        mnuBookingReport = new javax.swing.JMenuItem();
        mnuAllBooking = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/parent form image final FINAL.png"))); // NOI18N

        mnuForm.setText("Forms");

        mnuItemInfo.setText("Item info");
        mnuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemInfoActionPerformed(evt);
            }
        });
        mnuForm.add(mnuItemInfo);

        mnuCategory.setText("Category");
        mnuCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoryActionPerformed(evt);
            }
        });
        mnuForm.add(mnuCategory);

        mnuBill.setText("Bill Generator");
        mnuBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBillActionPerformed(evt);
            }
        });
        mnuForm.add(mnuBill);

        mnuBooking.setText("Book Table");
        mnuBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBookingActionPerformed(evt);
            }
        });
        mnuForm.add(mnuBooking);

        jMenuBar1.add(mnuForm);

        jMenu2.setText("Reports");

        mnuSearch.setText("Search Bill");
        mnuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSearch);

        mnuAllBills.setText("All Bills");
        mnuAllBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAllBillsActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAllBills);

        mnuBookingReport.setText("Booking Report");
        mnuBookingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBookingReportActionPerformed(evt);
            }
        });
        jMenu2.add(mnuBookingReport);

        mnuAllBooking.setText("All Booking");
        mnuAllBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAllBookingActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAllBooking);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemInfoActionPerformed
        ItemInfoForm frmItemInfoForm = new ItemInfoForm();
        frmItemInfoForm.setVisible(true);
    }//GEN-LAST:event_mnuItemInfoActionPerformed

    private void mnuCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoryActionPerformed
        CategoryForm frmCategoryForm = new CategoryForm();
        frmCategoryForm.setVisible(true);
    }//GEN-LAST:event_mnuCategoryActionPerformed

    private void mnuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchActionPerformed
        SearchBillForm frmSearchBillForm = new SearchBillForm();
        frmSearchBillForm.setVisible(true);
    }//GEN-LAST:event_mnuSearchActionPerformed

    private void mnuAllBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAllBillsActionPerformed
        ShowBillForm frmShowBillForm = new ShowBillForm();
        frmShowBillForm.setVisible(true);
    }//GEN-LAST:event_mnuAllBillsActionPerformed

    private void mnuBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBillActionPerformed
        BillForm frmBillForm = new BillForm();
        frmBillForm.setVisible(true);
    }//GEN-LAST:event_mnuBillActionPerformed

    private void mnuBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBookingActionPerformed
        TableBooking frmTableBooking = new TableBooking();
        frmTableBooking.setVisible(true);
    }//GEN-LAST:event_mnuBookingActionPerformed

    private void mnuBookingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBookingReportActionPerformed
        TableReport frmTableReport = new TableReport();
        frmTableReport.setVisible(true);
    }//GEN-LAST:event_mnuBookingReportActionPerformed

    private void mnuAllBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAllBookingActionPerformed
        ShowAllBooking frmShowAllBooking = new ShowAllBooking();
        frmShowAllBooking.setVisible(true);
    }//GEN-LAST:event_mnuAllBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuAllBills;
    private javax.swing.JMenuItem mnuAllBooking;
    private javax.swing.JMenuItem mnuBill;
    private javax.swing.JMenuItem mnuBooking;
    private javax.swing.JMenuItem mnuBookingReport;
    private javax.swing.JMenuItem mnuCategory;
    private javax.swing.JMenu mnuForm;
    private javax.swing.JMenuItem mnuItemInfo;
    private javax.swing.JMenuItem mnuSearch;
    // End of variables declaration//GEN-END:variables
}
