/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author 12a24
 */
public class SearchBillForm extends javax.swing.JFrame {

   Connection con;
    ResultSet rs;
    Statement stmt1, stmt2, stmt;
    ResultSet rs1, rs2;
    DefaultComboBoxModel model1;
    public SearchBillForm() {
        initComponents();
        txtDate.setEnabled(false);
        txtGrandTotal.setEnabled(false);
        
        
        try
        {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantbilling12a","root","root");
        stmt = con.createStatement();
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBillNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        btnDeleteBill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBillNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter Bill No");

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mypackage/search button.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date of Billing");

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Rate", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblBill);

        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrandTotalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Grand Total");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name of Customer");

        txtCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnDeleteBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteBill.setText("Delete bill");
        btnDeleteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBillActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteBill)))
                .addGap(68, 158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(195, 195, 195)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(110, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrandTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrandTotalActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        try
        {
            String billno = txtBillNo.getText();
            String customer = txtCustomer.getText();
            String getCustomer, getBillNo;
            if (billno.equals("") && customer.length()!=0 )
            {String q = "select * from bill where name ='"+customer+"'";
            txtBillNo.setText("");
            
            rs = stmt.executeQuery(q);
            DefaultTableModel m = (DefaultTableModel)tblBill.getModel();
            String name = "", rate = "" , qty="", amt="", date="";
            
            int rcount = tblBill.getRowCount();
            
            for (int i =0; i<rcount;i++)
            {
               m.removeRow(0);
            }
            
            
             while (rs.next())
                {
                
                        name = rs.getString("item");
                        rate = rs.getString("rate");
                        qty = rs.getString("qty");
                        amt = rs.getString("amount");
                        date = rs.getString("dateofbill");
                        getBillNo = rs.getString("billno");
                        m.addRow(new Object[]{name,rate,qty,amt});
                        txtDate.setText(date);
                        txtBillNo.setText(getBillNo);
                }
             String sum = "select sum(amount) from bill where name = '"+customer+"'";
             rs = stmt.executeQuery(sum);
             rs.first();
             
             String gt = rs.getString("sum(amount)");
             txtGrandTotal.setText(gt);
            }
            else if (customer.equals("") && billno.length()!=0 )
            {String q = "select * from bill where billno ="+billno+"";
            
            rs = stmt.executeQuery(q);
            DefaultTableModel m = (DefaultTableModel)tblBill.getModel();
            String name = "", rate = "" , qty="", amt="", date="";
            
            int rcount = tblBill.getRowCount();
            
            for (int i =0; i<rcount;i++)
            {
               m.removeRow(0);
            }
            
            
             while (rs.next())
                {
                
                        name = rs.getString("item");
                        rate = rs.getString("rate");
                        qty = rs.getString("qty");
                        amt = rs.getString("amount");
                        date = rs.getString("dateofbill");
                        m.addRow(new Object[]{name,rate,qty,amt});
                        txtDate.setText(date);
                        getCustomer = rs.getString("name");
                        txtCustomer.setText(getCustomer);
                }
             String sum = "select sum(amount) from bill where billno = "+billno;
             rs = stmt.executeQuery(sum);
             rs.first();
             
             String gt = rs.getString("sum(amount)");
             txtGrandTotal.setText(gt);
            }
            
            else if (customer.length()!=0 && billno.length()!=0) 
                
            {String q = "select * from bill where billno ="+billno+"";
            
            rs = stmt.executeQuery(q);
            DefaultTableModel m = (DefaultTableModel)tblBill.getModel();
            String name = "", rate = "" , qty="", amt="", date="";
            
            
            int rcount = tblBill.getRowCount();
            
            for (int i =0; i<rcount;i++)
            {
               m.removeRow(0);
            }
            
            
             while (rs.next())
                {
                
                        name = rs.getString("item");
                        rate = rs.getString("rate");
                        qty = rs.getString("qty");
                        amt = rs.getString("amount");
                        date = rs.getString("dateofbill");
                        m.addRow(new Object[]{name,rate,qty,amt});
                        txtDate.setText(date);
                }
             String sum = "select sum(amount) from bill where billno = "+billno;
             rs = stmt.executeQuery(sum);
             rs.first();
             
             String gt = rs.getString("sum(amount)");
             txtGrandTotal.setText(gt);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "please enter the billno or the customer name");
            }
             
             
                 
                
                
        
        }
        
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null, e);
        
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBillActionPerformed
      if(txtBillNo.getText().length()!=0)
      {
          String billno = txtBillNo.getText();
          try{
              int i = JOptionPane.showConfirmDialog(null, "Do you really want to delete this bill?");
              if(i==0)
              {
              String query = "delete from bill where billno ="+billno;
              stmt.executeUpdate(query);
              JOptionPane.showMessageDialog(null, "record permanently deleted");
              
              }
              else
              {
              JOptionPane.showMessageDialog(null, "cancelled");
              }
          
          }
          
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null, e);
          }
      
      
      
      }
      else
      {
      JOptionPane.showMessageDialog(null, "please enter the billno");
      
      }
    }//GEN-LAST:event_btnDeleteBillActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtBillNo.setText("");
        txtCustomer.setText("");
        txtDate.setText("");
        txtGrandTotal.setText("");
        DefaultTableModel dm = (DefaultTableModel)tblBill.getModel();
        dm.getDataVector().removeAllElements();;
        dm.fireTableDataChanged();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteBill;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGrandTotal;
    // End of variables declaration//GEN-END:variables
}
