/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author abhin
 */
public class TableBooking extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement stmt;
    int SeatTrack[][] = {{0, 0, 0}, {0, 0, 0}, {0, 0, 0}};

    public TableBooking() {
        initComponents();

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurantbilling12a", "root", "root");
            stmt = con.createStatement();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tglSeatA1 = new javax.swing.JToggleButton();
        tglSeatA2 = new javax.swing.JToggleButton();
        tglSeatB1 = new javax.swing.JToggleButton();
        tglSeatB2 = new javax.swing.JToggleButton();
        tglSeatB3 = new javax.swing.JToggleButton();
        tglSeatC1 = new javax.swing.JToggleButton();
        tglSeatC2 = new javax.swing.JToggleButton();
        tglSeatC3 = new javax.swing.JToggleButton();
        tglSeatA3 = new javax.swing.JToggleButton();
        dteDate = new com.toedter.calendar.JDateChooser();
        btnBook = new javax.swing.JButton();
        cmbTimeHour = new javax.swing.JComboBox<>();
        cmbTimeMinute = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtC_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMobNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOccasion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBookingID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Table Booking");

        tglSeatA1.setText("A1");
        tglSeatA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatA1ActionPerformed(evt);
            }
        });

        tglSeatA2.setText("A2");
        tglSeatA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatA2ActionPerformed(evt);
            }
        });

        tglSeatB1.setText("B1");
        tglSeatB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatB1ActionPerformed(evt);
            }
        });

        tglSeatB2.setText("B2");
        tglSeatB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatB2ActionPerformed(evt);
            }
        });

        tglSeatB3.setText("B3");
        tglSeatB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatB3ActionPerformed(evt);
            }
        });

        tglSeatC1.setText("C1");
        tglSeatC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatC1ActionPerformed(evt);
            }
        });

        tglSeatC2.setText("C2");
        tglSeatC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatC2ActionPerformed(evt);
            }
        });

        tglSeatC3.setText("C3");
        tglSeatC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatC3ActionPerformed(evt);
            }
        });

        tglSeatA3.setText("A3");
        tglSeatA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglSeatA3ActionPerformed(evt);
            }
        });

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        cmbTimeHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));

        cmbTimeMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jLabel3.setText("Time");

        jLabel5.setText("Date");

        jLabel6.setText("Customer Name");

        jLabel7.setText("Mobile No.");

        jLabel8.setText("Occasion (Optional)");

        jLabel9.setText("Booking ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglSeatA3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(tglSeatA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tglSeatA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(82, 82, 82)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOccasion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatB3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tglSeatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(btnBook)
                                                .addGap(120, 129, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tglSeatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tglSeatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtC_name, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(dteDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtC_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMobNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOccasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cmbTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tglSeatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglSeatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tglSeatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tglSeatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tglSeatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglSeatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBook))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed

        try {
            String book_id, name, mobno, occasion, date, time_hr, time_min;

            book_id = txtBookingID.getText();
            name = txtC_name.getText();
            mobno = txtMobNo.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            date = sdf.format(dteDate.getDate());
            time_hr = cmbTimeHour.getSelectedItem().toString();
            time_min = cmbTimeMinute.getSelectedItem().toString();
            occasion = txtOccasion.getText();

            ArrayList<String> seatsSelected = new ArrayList<String>();

            if (tglSeatA1.isSelected()) {
                seatsSelected.add("A1");
            }
            if (tglSeatA2.isSelected()) {
                seatsSelected.add("A2");
            }
            if (tglSeatA3.isSelected()) {
                seatsSelected.add("A3");
            }
            if (tglSeatB1.isSelected()) {
                seatsSelected.add("B1");
            }
            if (tglSeatB2.isSelected()) {
                seatsSelected.add("B2");
            }
            if (tglSeatB3.isSelected()) {
                seatsSelected.add("B3");
            }
            if (tglSeatC1.isSelected()) {
                seatsSelected.add("C1");
            }
            if (tglSeatC2.isSelected()) {
                seatsSelected.add("C2");
            }
            if (tglSeatC3.isSelected()) {
                seatsSelected.add("C3");
            }

            int len = seatsSelected.size();

            for (int i = 0; i < len; i++) {
                
                String q = "Insert into tablebooking values ('"+seatsSelected.get(i)+"', '"+name+"', "+mobno+", '"+date+" "+time_hr+":"+time_min+":00', '"+occasion+"', "+book_id+")";
                stmt.executeUpdate(q);
            }
            JOptionPane.showMessageDialog(null, "Booked!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void tglSeatA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatA1ActionPerformed
        if (tglSeatA1.isSelected()) {
            SeatTrack[0][0] = 1;

        } else if (tglSeatA1.isSelected() == false) {
            SeatTrack[0][0] = 0;
        }


    }//GEN-LAST:event_tglSeatA1ActionPerformed

    private void tglSeatA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatA2ActionPerformed
        if (tglSeatA2.isSelected()) {
            SeatTrack[1][0] = 1;

        } else if (tglSeatA2.isSelected() == false) {
            SeatTrack[1][0] = 0;
        }
    }//GEN-LAST:event_tglSeatA2ActionPerformed

    private void tglSeatA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatA3ActionPerformed
        if (tglSeatA3.isSelected()) {
            SeatTrack[2][0] = 1;

        } else if (tglSeatA3.isSelected() == false) {
            SeatTrack[2][0] = 0;
        }
    }//GEN-LAST:event_tglSeatA3ActionPerformed

    private void tglSeatB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatB1ActionPerformed
        if (tglSeatB1.isSelected()) {
            SeatTrack[0][1] = 1;

        } else if (tglSeatB1.isSelected() == false) {
            SeatTrack[0][1] = 0;
        }
    }//GEN-LAST:event_tglSeatB1ActionPerformed

    private void tglSeatB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatB2ActionPerformed
        if (tglSeatB2.isSelected()) {
            SeatTrack[1][1] = 1;

        } else if (tglSeatB2.isSelected() == false) {
            SeatTrack[1][1] = 0;
        }
    }//GEN-LAST:event_tglSeatB2ActionPerformed

    private void tglSeatB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatB3ActionPerformed
        if (tglSeatB3.isSelected()) {
            SeatTrack[2][1] = 1;

        } else if (tglSeatB3.isSelected() == false) {
            SeatTrack[2][1] = 0;
        }
    }//GEN-LAST:event_tglSeatB3ActionPerformed

    private void tglSeatC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatC1ActionPerformed
        if (tglSeatC1.isSelected()) {
            SeatTrack[0][2] = 1;

        } else if (tglSeatC1.isSelected() == false) {
            SeatTrack[0][2] = 0;
        }
    }//GEN-LAST:event_tglSeatC1ActionPerformed

    private void tglSeatC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatC2ActionPerformed
        if (tglSeatC2.isSelected()) {
            SeatTrack[1][2] = 1;

        } else if (tglSeatC2.isSelected() == false) {
            SeatTrack[1][2] = 0;
        }
    }//GEN-LAST:event_tglSeatC2ActionPerformed

    private void tglSeatC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglSeatC3ActionPerformed
        if (tglSeatC3.isSelected()) {
            SeatTrack[2][2] = 1;

        } else if (tglSeatC3.isSelected() == false) {
            SeatTrack[2][2] = 0;
        }
    }//GEN-LAST:event_tglSeatC3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox<String> cmbTimeHour;
    private javax.swing.JComboBox<String> cmbTimeMinute;
    private com.toedter.calendar.JDateChooser dteDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton tglSeatA1;
    private javax.swing.JToggleButton tglSeatA2;
    private javax.swing.JToggleButton tglSeatA3;
    private javax.swing.JToggleButton tglSeatB1;
    private javax.swing.JToggleButton tglSeatB2;
    private javax.swing.JToggleButton tglSeatB3;
    private javax.swing.JToggleButton tglSeatC1;
    private javax.swing.JToggleButton tglSeatC2;
    private javax.swing.JToggleButton tglSeatC3;
    private javax.swing.JTextField txtBookingID;
    private javax.swing.JTextField txtC_name;
    private javax.swing.JTextField txtMobNo;
    private javax.swing.JTextField txtOccasion;
    // End of variables declaration//GEN-END:variables
}
